controller:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['front_left_joint','back_left_joint']
    right_wheel: ['front_right_joint','back_right_joint']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25
    enable_odom_tf: true

    wheel_separation: 1
    wheel_radius: 0.2

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
